# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias python=python3
alias be="bundle exec"
alias beprepared="bundle exec rake db:migrate db:test:prepare && bundle exec rake parallel:prepare"
alias beseed="bundle exec rake versus:admin:mega_seed STATIC=true ROUNDS=2"

alias gga="git add"
alias ggb="git branch"
alias ggbD="git branch -D"
alias ggbd="git branch -d"
alias ggd="git diff"
alias ggdc="git diff --cached"
alias ggl="git log"
alias ggp="git pull"
alias ggpr="git pull --rebase"
alias ggr="git reset"
alias ggst="git status"
alias ggc="git commit"
alias ggcm="git commit -m"
alias ggca="git commit --amend -CHEAD"
alias ggs="git stash"
alias ggsl="git stash list"
alias ggsp="git stash pop"
alias ggsh="git show"
alias ggP="git push"
alias ggc="git checkout"
alias ggpb="git push -u origin"
alias ggrbc="git rebase --continue"
alias ggrbs="git rebase --skip"
